#!/usr/bin/env bash
# Install Haproxy and configure two servers to be load-balanced

sudo apt-get install --no-install-recommends -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
listen load_balancer
   bind 0.0.0.0:80
   mode http
   stats enable
   stats uri /haproxy?stats
   balance roundrobin
   option httpclose
   option forwardfor
   server 192-web-01 34.138.173.41:80 check
   server 192-web-02 34.73.165.69:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
