#!/usr/bin/env bash
# Configures an Ubuntu server with the following requirements:
# 	     - localhost resolves to 127.0.0.2
#	     - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2    localhost" > ~/hosts.alter
echo "8.8.8.8      facebook.com" >> ~/hosts.alter
cat ~/hosts.new > /etc/hosts
